name: lint-test-build-push
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: '>=1.22.2'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7
        with:
          version: latest
      
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Put fixture in place
        run: cp antibot.example.yaml antibot.yaml

      - name: Test with the Go CLI
        run: go test -v -race ./...

  build-push-ghcr:
    needs: [lint-test]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
